freeAgent/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^freeAgentApp/', include ('freeAgentApp.urls'))
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

freeAgentApp/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name='freeAgentApp'

urlpatterns = [

    # /freeAgentApp/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /freeAgentApp/register
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    # /freeAgentApp/login
    url(r'^login/$', views.Login.as_view(), name='login'),
    # /freeAgentApp/logout
    url(r'^logout/$', views.LogOut.as_view(), name='logout'),
    # /freeAgentApp/13/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /freeAgentApp/project/add/
    url(r'project/add/$', views.ProjectCreate.as_view(), name='createProject'),
    # /freeAgentApp/upload
    url(r'project/upload/(?P<pk>[\w-]+)$', views.ProjectUpload.as_view(), name='Upload'),
    # /freeAgentApp/project/2/
    url(r'project/(?P<pk>[0-9]+)/$', views.ProjectUpdate.as_view(), name='updateProject'),
    # /freeAgentApp/project/2/delete/
    url(r'project/(?P<pk>[0-9]+)/delete/$', views.ProjectDelete.as_view(), name='deleteProject'),
    # /freeAgent/workerIndex
    url(r'^workerIndex/$', views.WorkerView.as_view(), name='workerIndex'),
    # /freeAgent/addWorker
    url(r'^addWorker/$', views.add_worker, name='addWorker'),
    # /freeAgent/serializerUsername
    url(r'^serializerUsername', views.UserSerializer.as_view(), name='userNameSerializer'),
    # ／freeAgentApp/SerializeProject/create
    url(r'^serializerProject/create', views.ProjectCreateAPI.as_view(), name='ProjectCreateSerializer'),
    # ／freeAgentApp/SerializeProject/manage
    url(r'^serializerProject/manage/(?P<pk>[0-9]+)/',
        views.ProjectUpdateAndDeleteAPI.as_view(),
        name='ProjectManageSerializer'),
    # /freeAgentApp/search
    url(r'^results/$', views.search, name='search'),
    # ／freeAgentApp/SerializeProject/list
    url(r'^serializerProject/list', views.ProjectListAPI.as_view(), name='ProjectListSerializer'),
    # /freeAgentApp/homePage-public
    url(r'^homepage-public/$', views.HomePageViewAuthFalse.as_view(), name='homeAuthFalse'),
    # /freeAgentApp/homePage
    url(r'^homepage/$', views.HomePageViewAuthTrue.as_view(), name='homeAuthTrue'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

freeAgentApp/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator 
from decimal import *
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User,AbstractUser


class UserProfile(AbstractUser):
    
    Identification = models.CharField(max_length=10, choices=(('F', 'freeAgent'), ('C', 'Client')))


class Project(models.Model):

    title = models.CharField(max_length=100)
    cost = models.DecimalField(max_digits=15, decimal_places=2)
    pub_date = timezone.now()

    # Status could be one of four. (New=1, Applied=2, Accepted && Working=3, Completed && Closed=4)
    status = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(4)])
    description = models.CharField(max_length=300)
    file_type = models.FileField(null=True, blank=True)
    client_upload = models.FileField(null=True, blank=True)
    client = models.ForeignKey(UserProfile, related_name="ThisClient", null=True, blank=True)
    worker = models.ForeignKey(UserProfile, related_name="ThisWorker", null=True, blank=True)
    
    def get_absolute_url(self):
        return reverse('freeAgentApp:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return "%s" % self.title
        
        
class Review(models.Model):
    
    # Client can only enter an integer between 0 & 10
    project = models.ForeignKey(Project, null=True, on_delete=models.CASCADE)
    project_rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])

    def __str__(self):
        return "%s" % self.project_rating

freeAgentApp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = UserProfile
        fields = ['username', 'email', 'password', 'first_name', 'last_name', 'Identification']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
        }


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput()
    )
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input'}))

freeAgentApp/views.py
from django.views import generic
from .models import Project, Review, UserProfile
from django.views.generic import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView, BaseFormView
from django.views.generic.base import TemplateView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth import authenticate, login
from .forms import UserForm, LoginForm
from rest_framework.generics import ListAPIView, RetrieveUpdateDestroyAPIView, CreateAPIView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import permissions
from django.core.exceptions import ValidationError
from rest_framework.response import Response
from rest_framework import status
from .serializer import ProjectSerializer, ProjectCreateSerializer, UserProfileSerializer
from django.http import HttpResponse, HttpResponseRedirect
import re
from django.db.models import Q


def add_worker(request):
    """Handles adding workers to projects and uploading code to projects.
    Called when a corresponding button is clicked on a project."""

    if request.method == "POST":    
        # Free Agent clicked 'add' button on a project
        if 'add' in request.POST:
            user = request.user
            project = Project.objects.get(id=request.POST["project.id"])

            if project.status == 1:
                project.worker = user
                project.status = 2
                project.save()
            else:
                return HttpResponseRedirect('../?message=1')
                # redirect('freeAgentApp:index')
            return redirect('freeAgentApp:workerIndex')

        # End Client accepts or rejects a Free Agent on a project
        if 'Accept' in request.POST:
            project = Project.objects.get(id=request.POST["project.id"])
            if project.status == 2:
                project.status = 3
                project.save()
            return redirect('freeAgentApp:detail', project.id)
        elif 'Refuse' in request.POST:
            project = Project.objects.get(id=request.POST["project.id"])
            project.status = 1
            project.worker = None
            project.save()
            return redirect('freeAgentApp:detail', project.id)

        # Free Agent uploads completed code submission to a project
        if 'UploadWork' in request.POST:
            project = Project.objects.get(id=request.POST["project.id"])
            project.save()
            return redirect('freeAgentApp:detail', project.id)

        # End Client confirms a completed code submission on a project
        if 'ConfirmWork' in request.POST:
            project = Project.objects.get(id=request.POST["project.id"])
            project.status = 4
            project.save()
            return redirect('freeAgentApp:detail', project.id)

    # We don't do GET requests!
    return redirect('freeAgentApp:index')


def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string into invidual keywords, getting rid of unecessary spaces '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]


def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.

    '''
    query = None # Query to search for every search term        
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query


def search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        print ('Query String is ' + query_string)
        entry_query = get_query(query_string, ['title','description',])
        found_entries = Project.objects.filter(entry_query).order_by('id')
        print (found_entries)
        
    return render(request,'freeAgentApp/results.html',{'found_entries':found_entries, 'query_string':query_string,})
                                         
                          
class UserFormView(View):
    """Registration form."""
    form_class = UserForm
    template_name = 'freeAgentApp/registration.html'

    # New form
    def get(self,request):
        if request.user.is_authenticated():
            return redirect('freeAgentApp:index')

        form = self.form_class()
        return render(request, self.template_name, {'form':form})

    # Completed form. Creates a new user.
    def post(self,request):
        form = self.form_class(request.POST)
           
        if form.is_valid():
           
            user = form.save(commit=False)
                
            # Get cleaned noramlised data - i.e. date entries etc
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Make sure the username is unique
            try:
                UserProfile.objects.get(username=username)
            except UserProfile.DoesNotExist:
                # Change user password
                user.set_password(password)
                user.save()

                # Authenticate and login the new user
                user = authenticate(username=username,password=password)
                if user is not None:
                    if user.is_active:
                        login(request, user)
                    return redirect('freeAgentApp:index')
                return render(request, self.template_name, {'form':form})

        # Registration failed
        return render(request, self.template_name, {'form': form})


class IndexView(LoginRequiredMixin, generic.ListView):
    """Displays a list of created projects for an End Client, and
    a list of all projects to a Free Agent.

    """
    template_name = 'freeAgentApp/index.html'

    def get_queryset(self):
        # Filter by username if the type of user is client
        user = self.request.user
        if user.Identification == 'C':
            return Project.objects.filter(client=user)
        else:
            return Project.objects.filter(status=1)


class HomePageViewAuthTrue(LoginRequiredMixin, TemplateView):
    """Logged-in home page."""
    template_name = 'freeAgentApp/homeAuthTrue.html'


class HomePageViewAuthFalse(TemplateView):
    """Logged-out home page."""
    template_name = 'freeAgentApp/homeAuthFalse.html'


class WorkerView(LoginRequiredMixin, generic.ListView):
    """Displays a list of all the projects an End Client has accepted."""

    model = Project
    template_name = 'freeAgentApp/workerIndex.html'
  
    def get_queryset(self):
        # Filter by username if the type of user is client
      
        user = self.request.user
        return Project.objects.filter(worker=user)
        
       
class DetailView(LoginRequiredMixin, generic.DetailView):
    """Detailed information for a given project."""

    model = Project
    template_name = 'freeAgentApp/detail.html'


class ProjectCreate(LoginRequiredMixin, CreateView):
    """Form to create a new project."""

    model = Project
    fields = ['title', 'cost', 'description', 'file_type']

    def form_valid(self, form):
        """Called when a form is valid and a new project is about to be saved."""
        # Calls default form_valid() method and saves a new project in self.object
        response = super(ProjectCreate, self).form_valid(form)

        # Set the project's client (the user that created the project) to be the current user
        self.object.client = self.request.user
        self.object.save()

        # Required by the CreateView view to return the reponse objects
        return response


class ProjectUpload(LoginRequiredMixin, UpdateView):
    model = Project
    fields = ['client_upload']


class ProjectUpdate(UpdateView):
    model = Project
    fields = ['title', 'cost', 'description', 'status']
 

class ProjectDelete(DeleteView):
    model = Project
    success_url = reverse_lazy('freeAgentApp:index')


class Login(LoginView):
    """Login page."""

    form_class = LoginForm
    template_name = "freeAgentApp/login.html"
    redirect_authenticated_user = True


class LogOut(LogoutView):
    pass


#
# RESTful API views
#

class UserSerializer(ListAPIView):
    queryset = UserProfile.objects.all()
    serializer_class = UserProfileSerializer


class ProjectListAPI(ListAPIView):
    serializer_class = ProjectSerializer
    permissions_class = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.Identification is 'C':
            self.queryset = Project.objects.filter(client=user)
            return self.queryset
        elif user.Identification is 'F':
            self.queryset = Project.objects.filter(worker=user)
            return self.queryset


class ProjectCreateAPI(CreateAPIView):
    # queryset = Project.objects.all()
    serializer_class = ProjectCreateSerializer
    permissions_class = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        if self.request.user.Identification == 'C':
            serializer.save(client=self.request.user)
        else:
            raise ValidationError('You are not allowed to create a project!')


class ProjectUpdateAndDeleteAPI(RetrieveUpdateDestroyAPIView):
    # queryset = Project.objects.all()

freeAgentApp/templates/freeAgentApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} Free Agent {% endblock %} </title>
    <!-- Loads a path to the static files & bootstrap-->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="../../static/freeAgentApp/css/style_cheesy.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% block head %}
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            <a class="navbar-brand" href="{%url 'freeAgentApp:homepage' %}">Free Agent</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'freeAgentApp:index' %}">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp;Project List
                    </a>
                </li>
            </ul>
            <!--Search-->
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'freeAgentApp:search' %}">
                <input type="text" id="searchBox" class="input-medium search-query" name="q" placeholder="">
                <button type="submit" class="btn btn-default"> Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    {% if user.Identification == 'C' %}
                    <a href="{% url 'freeAgentApp:createProject' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Project
                    </a>
                    {% else %}
                    <a href="{% url 'freeAgentApp:workerIndex' user.id %}">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp;My Projects
                    </a>
                    {% endif %}
                </li>
                <li class="">
                    <a>Username: {{ user.username }} </a>
                </li>
                <li>

                </li>
                <li class="">
                    <a href="{% url 'freeAgentApp:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Log Out
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

freeAgentApp/templates/freeAgentApp/detail.html
{% extends 'freeAgentApp/base.html' %}
{% block title %} Project Detail {% endblock %}

{% block body %}
<div class="page-header">
    <div class="container"><h3>Project Details</h3></div>
</div>

<div class="jumbotron">
    <div class="container">
        <h6> Title: {{project.title}}</h6>
        <h6> Cost: {{project.cost}}</h6>
        <h6> Status:
            {% if project.status == 1 %} New Project

            {% elif project.status == 2 %} Applied

            {% elif project.status == 3 %} Working

            {% elif project.status == 4 %} Completed

            {% endif %}
        </h6>
        <h6> Description: {{project.description}}</h6>
        <h6> Posted Date: {{project.pub_date}}</h6>
        <h6> Worker: {{project.worker }}</h6>
        <h6> Client: {{ project.client }}</h6>
        {% if user.Identification == 'C' %}
            {% if project.status == 2 %}
                <form action="{% url 'freeAgentApp:addWorker'  %}" method="post" style=" display: inline;">
                    {%csrf_token%}
                    <input  name = "project.id" type="hidden" value="{{project.id }}" />
                    <button type="submit" name ="Accept" class="btn btn-default btn-sm"> Accept Worker</button>

                    <button type="submit" name ="Refuse" class="btn btn-default btn-sm"> Refuse Worker</button>
                </form>
            {% elif project.status == 3%}
                <h6>
                    Client's Work:
                    {% if project.client_upload%}
                        <a href="{{ project.client_upload.url }}" >{{ project.client_upload}}</a>
                    {% else %}
                        None
                    {% endif %}
                </h6>
                <form action="{% url 'freeAgentApp:addWorker'  %}" method="post" style=" display: inline" enctype="multipart/form-data">
                    {%csrf_token%}
                    <input  name = "project.id" type="hidden" value="{{project.id }}" />
                    <button type="submit" name ="ConfirmWork" class="btn btn-default btn-sm"> Confirm Work</button>
                </form>
            {% elif project.status == 4 %}
                <h6>
                    Client's Work:
                    {% if project.client_upload%}
                        <a href="{{ project.client_upload.url }}" download="{{ project.title }}">{{ project.client_upload}}</a>
                    {% else %}
                        None
                    {% endif %}    
                </h6>
            {% endif %}
        {% endif %}
        {% if user.Identification == 'F' %}
            {% if project.status == 3 %}

                <form action="{% url 'freeAgentApp:addWorker'  %}" method="post" style="display: inline" enctype="multipart/form-data">
                    {%csrf_token%}
                    <h6>
                    Client's Work:
                    {{ project.client_upload }}
                        <div>
                            <a href="{% url 'freeAgentApp:Upload' project.id %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;UpLoad
                        </a>
                        </div>
                    </h6>
                    <input  name = "project.id" type="hidden" value="{{project.id }}" />
                    <button name ="UploadWork" class="btn btn-default btn-sm"> Upload Work</button>
                </form>
            {% elif project.status == 4 %}
                <h6>
                    Client's Work:
                    <a href="{{ project.client_upload.url }}" download="{{ project.title }}">{{ project.client_upload}}</a>
                </h6>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}

freeAgentApp/templates/freeAgentApp/form-template.html
{% for field in form %}
    <div class="form-group" >
        <label class="col-sm-4 control-label-self-define" id="{{ field.label }}">{{ field.label_tag}}</label>
        {{ field }}
        <p id="pTag-{{ field.label }}" ></p>
        <div class ="col-sm-offset-1">
            <span class = "text-danger small">{{field.errors}} </span>
        </div>
    </div>
{% endfor %}

freeAgentApp/templates/freeAgentApp/homeAuthFalse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} Free Agent {% endblock %} </title>
    <!-- Loads a path to the static files & bootstrap-->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '/freeAgentApp/style/style.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}

    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;}
    }
    </style>
    <style>
        .navbar         { border-radius:0;}
        .navbar-brand   {font-family:'Satisfy',cursive; font-size:60}
    </style>
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!--Header-->
        <div class="navbar-header">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="#">Free Agent</a>
            <!--<a href="{% url 'freeAgentApp:login' %}">-->
            <!--<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Log In-->
            <!--</a>-->
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'freeAgentApp:login' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Log In/Register
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% include "freeAgentApp/about.html" %}
{% endblock %}
</body>
</html>

freeAgentApp/templates/freeAgentApp/homeAuthTrue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} Free Agent {% endblock %} </title>
    <!-- Loads a path to the static files & bootstrap-->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="../../static/freeAgentApp/css/style_cheesy.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}

    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;}
    }
    </style>
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>


            <a class="navbar-brand" href="{%url 'freeAgentApp:homeAuthTrue' %}">Free Agent</a>
        </div>

        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'freeAgentApp:index' %}">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp;Project List
                    </a>
                </li>
            </ul>
            <!--Search-->
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'freeAgentApp:search' %}">
                <input type="text" id="searchBox" class="input-medium search-query" name="q" placeholder="">
                <button type="submit" class="btn btn-default"> Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    {% if user.Identification == 'C' %}
                    <a href="{% url 'freeAgentApp:createProject' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Project
                    </a>
                    {% else %}
                    <a href="{% url 'freeAgentApp:workerIndex' user.id %}">
                        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>&nbsp;My Projects
                    </a>
                    {% endif %}
                </li>
                <li class="">
                    <a>Username: {{ user.username }} </a>
                </li>
                <li>

                </li>
                <li class="">
                    <a href="{% url 'freeAgentApp:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Log Out
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}
{% include "freeAgentApp/about.html" %}
{% endblock %}

</body>
</html>

freeAgentApp/templates/freeAgentApp/index.html
{% extends 'freeAgentApp/base.html' %}
{% block title %} All Projects {% endblock %}

{% block body %}

{{ error }}

<div class="page-header">
    {% if user.Identification == 'F' %}
        <div class="container"><h3>FreeAgent - Available Projects</h3></div>
    {% else %}
        <div class="container"><h3>My Created Projects</h3></div>
    {% endif %}
</div>

{% for project in object_list %}
<!--Details-->
<ul>
    <div class="col-md-4">
        <div class="jumbotron">
            <div class="container">
                <h4><a href="{% url 'freeAgentApp:detail' project.id %}">{{project.title}}</a></h4>
                <h6>Cost: {{project.cost}}</h6>
                <h6>Description: {{project.description}}</h6>
                <h6> Status:
                    {% if project.status == 1 %} New Project

                    {% elif project.status == 2 %} Applied

                    {% elif project.status == 3 %} Working

                    {% elif project.status == 4 %} Completed

                    {% endif %}
                </h6>

                <!--Delete or Accept-->
                {% if user.Identification == 'C' %}
                <form action="{% url 'freeAgentApp:deleteProject' project.id %}" method="post" style=" display: inline;">
                    {%csrf_token%}
                    <!--<input type="Button" name="project_id" value="{{project.id}}">-->
                    <button type="submit" class="btn btn-default btn-sm"> Delete
                        <span class="glyphicon glyphicon-trash"></span></button>
                </form>
                {% else %}
                <form action="{% url 'freeAgentApp:addWorker'  %}" method="post" style=" display: inline;">
                    {%csrf_token%}
                    <!--<Get rid of this and name button and then call button in views.py within add">-->
                    <input id="project.id" name = "project.id" type="hidden" value="{{project.id }}">
                    <button type="submit" name ="add" class="btn btn-default btn-sm"> Add
                        <span class="glyphicon glyphicon-plus"></span></button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</ul>

{% endfor %}
    <script>
    var url = window.location.search;
    var message = url[url.lastIndexOf('=')+1];
    if(message == '1'){
        alert('Sorry, someone has already applied this project!');
    }

    </script>
{% endblock %}